# Site settings
title: "R.zip Land"
author: "Captain R.zip"
description: "This is a blog about data-science. Posts are mainly about studies from R.zip"
keywords: "Linear Algebra, ISLR, Machine Learning, R.zip Story, Regression, NLP"
biography: "R.zip is institution of SungKyunKwan University. Started from Statistical Psychology, we are spreading our endeavor to data science"
colophon: "will be added if this still exists"

baseurl: ""
url: "https://rziphome.github.io"

twitter_username: ferreira_hugo
github_username: hugoferreira
linkedin_username: hugoserenoferreira
facebook_username: hugo.sereno.ferreira
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
